### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marefati110**

### CODE REVIEW

**Comment by honzaap** [comment]
I dont understand... ```npm run start``` runs ```ng serve``` anyways. There is literally no difference...

**Comment by Anthony00107** [comment]
- [x] Hello everyone my name is Anthony, I got this app for help. I'm not going to sound like a little girl rn but I'm also homeless and ineed of money and a new car the car I have now battery went out and nobody is willing to help me I've been in this parking lot for about 3 weeks now. And it's hell. The reason I'm saying all this is because my parents died 2 mouths ago and the court split all my brothers and sisters but not me im 22 now and the judge tell me im in no condition financially and unstable with ptsd and sever depression. Can I get advice? I'll do whatever it takes to be a team player in how we our work. Thank you for your time in reading this for those that did

**Comment by marefati110** [comment]
to run project should use `npm run ng serve` or `npm run start` not `ng serve`

**Comment by honzaap** [comment]
Ok, but why? What is the difference? The project was created using Angular CLI, running ```ng serve``` to start a project is a standard procedure, there is nothing wrong or bad with it...

**Comment by marefati110** [comment]
The difference is that when someone does not installed `ng` globally on their system, they can not start the project and receive an error its good that the execution of the project does not depend on a specific program that must installed before.

**Comment by honzaap** [comment]
Oh ok, that makes sense... you should've said that from the start, I'll merge it then.

**Pull request merged**
